import img1 from "../../../assets/img/pages/committee/1.jpg"
import img2 from "../../../assets/img/pages/committee/2.jpg"
import img3 from "../../../assets/img/pages/committee/3.jpg"
import img4 from "../../../assets/img/pages/committee/4.jpg"
import img5 from "../../../assets/img/pages/committee/1.jpg"
import img6 from "../../../assets/img/pages/committee/2.jpg"
import img7 from "../../../assets/img/pages/committee/3.jpg"
import img8 from "../../../assets/img/pages/committee/4.jpg"

export const data = [
  {
    id: 1,
    img: img1,
    title: "dr. ashraf ganie",
    designation: "President MPPCOS Society",
    institute: "AIIMS, Apollo, Osmania Medical Collage",
    details: "Prof. Krishnan Balasubramaniam has been involved in the field of Non-destructive evaluation for more than Thirty years with applications in the fields of maintenance, quality assurance, manufacturing and design. His areas of research interests include Nondestructive evaluation, in-process monitoring, structural health monitoring, and applied data analysis. He is currently a Chair Professor in the Department of Mechanical Engineering and the Dean for Industrial Consultancy and Sponsored Research at the Indian Institute of Technology Madras, and also serves as the Head of the Centre for Nondestructive Evaluation which he founded in 2001. He received his undergraduate degree in Mechanical Engineering from the University of Madras (Regional Engineering College, Tiruchirapalli, India) in 1984. He then graduated from Drexel University with a M.S. degree in 1986 and a Ph.D. in the year 1989. Before joining IIT Madras in 2000, he was employed at Mississippi State University. He has over 400 technical publications (including 200 refereed journal papers), 16 patents filings and has directed 22 PHD student dissertations and 46 MS student theses. In recognition for his outstanding contributions to research in the field of Nondestructive Evaluation, he was conferred with the ROY SHARPE PRIZE by the British Institute for NDT for the year 2012. He was also awarded the ISTEM Entrepreneurial Faculty Member Award for his entrepreneurial activities by Auburn University, USA in 2011 and the NATIONAL NDT AWARD 2010 by the Indian Society for NDT. He also was conferred the DRDO Academy Excellence Award for 2015. He has also been bestowed with the prestigious ABDUL KALAM National Technology Innovation Fellowship in 2018. He has been instrumental in the incubation of several startups including Dhvani Research, Playns Technologies, Detect Technologies, Maximl Labs, Trotix Robotics, HyperVerge, and OP Tech and has jointly developed several new products through these companies. He currently serves as the Editor-in-Chief of the Journal for Nondestructive Evaluation (ISNT) and as the South-east Asia Editor for the Journal of Nondestructive Testing and Evaluation (Taylor and Francis). He also serves as the Associate Editor of Ultrasonics (Elsevier) and serves in the editorial board of the Journal of Structural Longevity (Techscience). He also is a board member of the World Federation of NDE Centers and the QNDE Scientific Advisor Committee. He is a Life Fellow of the Academia NDT International, Life Fellow of the Indian Society of Nondestructive Testing (ISNT) and a Fellow of the Indian National Academy of Engineers."
  },
  {
    id: 2,
    img: img2,
    title: "dr. rakesh sahay",
    designation: "Organising Chairman",
    institute: "AIIMS, Apollo, Osmania Medical Collage",
    details: "Prof. Krishnan Balasubramaniam has been involved in the field of Non-destructive evaluation for more than Thirty years with applications in the fields of maintenance, quality assurance, manufacturing and design. His areas of research interests include Nondestructive evaluation, in-process monitoring, structural health monitoring, and applied data analysis. He is currently a Chair Professor in the Department of Mechanical Engineering and the Dean for Industrial Consultancy and Sponsored Research at the Indian Institute of Technology Madras, and also serves as the Head of the Centre for Nondestructive Evaluation which he founded in 2001. He received his undergraduate degree in Mechanical Engineering from the University of Madras (Regional Engineering College, Tiruchirapalli, India) in 1984. He then graduated from Drexel University with a M.S. degree in 1986 and a Ph.D. in the year 1989. Before joining IIT Madras in 2000, he was employed at Mississippi State University. He has over 400 technical publications (including 200 refereed journal papers), 16 patents filings and has directed 22 PHD student dissertations and 46 MS student theses. In recognition for his outstanding contributions to research in the field of Nondestructive Evaluation, he was conferred with the ROY SHARPE PRIZE by the British Institute for NDT for the year 2012. He was also awarded the ISTEM Entrepreneurial Faculty Member Award for his entrepreneurial activities by Auburn University, USA in 2011 and the NATIONAL NDT AWARD 2010 by the Indian Society for NDT. He also was conferred the DRDO Academy Excellence Award for 2015. He has also been bestowed with the prestigious ABDUL KALAM National Technology Innovation Fellowship in 2018. He has been instrumental in the incubation of several startups including Dhvani Research, Playns Technologies, Detect Technologies, Maximl Labs, Trotix Robotics, HyperVerge, and OP Tech and has jointly developed several new products through these companies. He currently serves as the Editor-in-Chief of the Journal for Nondestructive Evaluation (ISNT) and as the South-east Asia Editor for the Journal of Nondestructive Testing and Evaluation (Taylor and Francis). He also serves as the Associate Editor of Ultrasonics (Elsevier) and serves in the editorial board of the Journal of Structural Longevity (Techscience). He also is a board member of the World Federation of NDE Centers and the QNDE Scientific Advisor Committee. He is a Life Fellow of the Academia NDT International, Life Fellow of the Indian Society of Nondestructive Testing (ISNT) and a Fellow of the Indian National Academy of Engineers."
  },
  {
    id: 3,
    img: img3,
    title: "dr. sanjay kalra",
    designation: "Chairman Scientific Committee",
    institute: "AIIMS, Apollo, Osmania Medical Collage",
    details: "Prof. Krishnan Balasubramaniam has been involved in the field of Non-destructive evaluation for more than Thirty years with applications in the fields of maintenance, quality assurance, manufacturing and design. His areas of research interests include Nondestructive evaluation, in-process monitoring, structural health monitoring, and applied data analysis. He is currently a Chair Professor in the Department of Mechanical Engineering and the Dean for Industrial Consultancy and Sponsored Research at the Indian Institute of Technology Madras, and also serves as the Head of the Centre for Nondestructive Evaluation which he founded in 2001. He received his undergraduate degree in Mechanical Engineering from the University of Madras (Regional Engineering College, Tiruchirapalli, India) in 1984. He then graduated from Drexel University with a M.S. degree in 1986 and a Ph.D. in the year 1989. Before joining IIT Madras in 2000, he was employed at Mississippi State University. He has over 400 technical publications (including 200 refereed journal papers), 16 patents filings and has directed 22 PHD student dissertations and 46 MS student theses. In recognition for his outstanding contributions to research in the field of Nondestructive Evaluation, he was conferred with the ROY SHARPE PRIZE by the British Institute for NDT for the year 2012. He was also awarded the ISTEM Entrepreneurial Faculty Member Award for his entrepreneurial activities by Auburn University, USA in 2011 and the NATIONAL NDT AWARD 2010 by the Indian Society for NDT. He also was conferred the DRDO Academy Excellence Award for 2015. He has also been bestowed with the prestigious ABDUL KALAM National Technology Innovation Fellowship in 2018. He has been instrumental in the incubation of several startups including Dhvani Research, Playns Technologies, Detect Technologies, Maximl Labs, Trotix Robotics, HyperVerge, and OP Tech and has jointly developed several new products through these companies. He currently serves as the Editor-in-Chief of the Journal for Nondestructive Evaluation (ISNT) and as the South-east Asia Editor for the Journal of Nondestructive Testing and Evaluation (Taylor and Francis). He also serves as the Associate Editor of Ultrasonics (Elsevier) and serves in the editorial board of the Journal of Structural Longevity (Techscience). He also is a board member of the World Federation of NDE Centers and the QNDE Scientific Advisor Committee. He is a Life Fellow of the Academia NDT International, Life Fellow of the Indian Society of Nondestructive Testing (ISNT) and a Fellow of the Indian National Academy of Engineers."
  },
  {
    id: 4,
    img: img4,
    title: "dr. jayaprakash sai",
    designation: "Organising Secretary",
    institute: "AIIMS, Apollo, Osmania Medical Collage",
    details: "Prof. Krishnan Balasubramaniam has been involved in the field of Non-destructive evaluation for more than Thirty years with applications in the fields of maintenance, quality assurance, manufacturing and design. His areas of research interests include Nondestructive evaluation, in-process monitoring, structural health monitoring, and applied data analysis. He is currently a Chair Professor in the Department of Mechanical Engineering and the Dean for Industrial Consultancy and Sponsored Research at the Indian Institute of Technology Madras, and also serves as the Head of the Centre for Nondestructive Evaluation which he founded in 2001. He received his undergraduate degree in Mechanical Engineering from the University of Madras (Regional Engineering College, Tiruchirapalli, India) in 1984. He then graduated from Drexel University with a M.S. degree in 1986 and a Ph.D. in the year 1989. Before joining IIT Madras in 2000, he was employed at Mississippi State University. He has over 400 technical publications (including 200 refereed journal papers), 16 patents filings and has directed 22 PHD student dissertations and 46 MS student theses. In recognition for his outstanding contributions to research in the field of Nondestructive Evaluation, he was conferred with the ROY SHARPE PRIZE by the British Institute for NDT for the year 2012. He was also awarded the ISTEM Entrepreneurial Faculty Member Award for his entrepreneurial activities by Auburn University, USA in 2011 and the NATIONAL NDT AWARD 2010 by the Indian Society for NDT. He also was conferred the DRDO Academy Excellence Award for 2015. He has also been bestowed with the prestigious ABDUL KALAM National Technology Innovation Fellowship in 2018. He has been instrumental in the incubation of several startups including Dhvani Research, Playns Technologies, Detect Technologies, Maximl Labs, Trotix Robotics, HyperVerge, and OP Tech and has jointly developed several new products through these companies. He currently serves as the Editor-in-Chief of the Journal for Nondestructive Evaluation (ISNT) and as the South-east Asia Editor for the Journal of Nondestructive Testing and Evaluation (Taylor and Francis). He also serves as the Associate Editor of Ultrasonics (Elsevier) and serves in the editorial board of the Journal of Structural Longevity (Techscience). He also is a board member of the World Federation of NDE Centers and the QNDE Scientific Advisor Committee. He is a Life Fellow of the Academia NDT International, Life Fellow of the Indian Society of Nondestructive Testing (ISNT) and a Fellow of the Indian National Academy of Engineers."
  },
  {
    id: 5,
    img: img1,
    title: "dr. ashraf ganie",
    designation: "President MPPCOS Society",
    institute: "AIIMS, Apollo, Osmania Medical Collage",
    details: "Prof. Krishnan Balasubramaniam has been involved in the field of Non-destructive evaluation for more than Thirty years with applications in the fields of maintenance, quality assurance, manufacturing and design. His areas of research interests include Nondestructive evaluation, in-process monitoring, structural health monitoring, and applied data analysis. He is currently a Chair Professor in the Department of Mechanical Engineering and the Dean for Industrial Consultancy and Sponsored Research at the Indian Institute of Technology Madras, and also serves as the Head of the Centre for Nondestructive Evaluation which he founded in 2001. He received his undergraduate degree in Mechanical Engineering from the University of Madras (Regional Engineering College, Tiruchirapalli, India) in 1984. He then graduated from Drexel University with a M.S. degree in 1986 and a Ph.D. in the year 1989. Before joining IIT Madras in 2000, he was employed at Mississippi State University. He has over 400 technical publications (including 200 refereed journal papers), 16 patents filings and has directed 22 PHD student dissertations and 46 MS student theses. In recognition for his outstanding contributions to research in the field of Nondestructive Evaluation, he was conferred with the ROY SHARPE PRIZE by the British Institute for NDT for the year 2012. He was also awarded the ISTEM Entrepreneurial Faculty Member Award for his entrepreneurial activities by Auburn University, USA in 2011 and the NATIONAL NDT AWARD 2010 by the Indian Society for NDT. He also was conferred the DRDO Academy Excellence Award for 2015. He has also been bestowed with the prestigious ABDUL KALAM National Technology Innovation Fellowship in 2018. He has been instrumental in the incubation of several startups including Dhvani Research, Playns Technologies, Detect Technologies, Maximl Labs, Trotix Robotics, HyperVerge, and OP Tech and has jointly developed several new products through these companies. He currently serves as the Editor-in-Chief of the Journal for Nondestructive Evaluation (ISNT) and as the South-east Asia Editor for the Journal of Nondestructive Testing and Evaluation (Taylor and Francis). He also serves as the Associate Editor of Ultrasonics (Elsevier) and serves in the editorial board of the Journal of Structural Longevity (Techscience). He also is a board member of the World Federation of NDE Centers and the QNDE Scientific Advisor Committee. He is a Life Fellow of the Academia NDT International, Life Fellow of the Indian Society of Nondestructive Testing (ISNT) and a Fellow of the Indian National Academy of Engineers."
  },
  {
    id: 6,
    img: img2,
    title: "rakesh sahay",
    designation: "Organising Chairman",
    institute: "AIIMS, Apollo, Osmania Medical Collage",
    details: "Prof. Krishnan Balasubramaniam has been involved in the field of Non-destructive evaluation for more than Thirty years with applications in the fields of maintenance, quality assurance, manufacturing and design. His areas of research interests include Nondestructive evaluation, in-process monitoring, structural health monitoring, and applied data analysis. He is currently a Chair Professor in the Department of Mechanical Engineering and the Dean for Industrial Consultancy and Sponsored Research at the Indian Institute of Technology Madras, and also serves as the Head of the Centre for Nondestructive Evaluation which he founded in 2001. He received his undergraduate degree in Mechanical Engineering from the University of Madras (Regional Engineering College, Tiruchirapalli, India) in 1984. He then graduated from Drexel University with a M.S. degree in 1986 and a Ph.D. in the year 1989. Before joining IIT Madras in 2000, he was employed at Mississippi State University. He has over 400 technical publications (including 200 refereed journal papers), 16 patents filings and has directed 22 PHD student dissertations and 46 MS student theses. In recognition for his outstanding contributions to research in the field of Nondestructive Evaluation, he was conferred with the ROY SHARPE PRIZE by the British Institute for NDT for the year 2012. He was also awarded the ISTEM Entrepreneurial Faculty Member Award for his entrepreneurial activities by Auburn University, USA in 2011 and the NATIONAL NDT AWARD 2010 by the Indian Society for NDT. He also was conferred the DRDO Academy Excellence Award for 2015. He has also been bestowed with the prestigious ABDUL KALAM National Technology Innovation Fellowship in 2018. He has been instrumental in the incubation of several startups including Dhvani Research, Playns Technologies, Detect Technologies, Maximl Labs, Trotix Robotics, HyperVerge, and OP Tech and has jointly developed several new products through these companies. He currently serves as the Editor-in-Chief of the Journal for Nondestructive Evaluation (ISNT) and as the South-east Asia Editor for the Journal of Nondestructive Testing and Evaluation (Taylor and Francis). He also serves as the Associate Editor of Ultrasonics (Elsevier) and serves in the editorial board of the Journal of Structural Longevity (Techscience). He also is a board member of the World Federation of NDE Centers and the QNDE Scientific Advisor Committee. He is a Life Fellow of the Academia NDT International, Life Fellow of the Indian Society of Nondestructive Testing (ISNT) and a Fellow of the Indian National Academy of Engineers."
  },
  {
    id: 7,
    img: img3,
    title: "dr. sanjay kalra",
    designation: "Chairman Scientific Committee",
    institute: "AIIMS, Apollo, Osmania Medical Collage",
    details: "Prof. Krishnan Balasubramaniam has been involved in the field of Non-destructive evaluation for more than Thirty years with applications in the fields of maintenance, quality assurance, manufacturing and design. His areas of research interests include Nondestructive evaluation, in-process monitoring, structural health monitoring, and applied data analysis. He is currently a Chair Professor in the Department of Mechanical Engineering and the Dean for Industrial Consultancy and Sponsored Research at the Indian Institute of Technology Madras, and also serves as the Head of the Centre for Nondestructive Evaluation which he founded in 2001. He received his undergraduate degree in Mechanical Engineering from the University of Madras (Regional Engineering College, Tiruchirapalli, India) in 1984. He then graduated from Drexel University with a M.S. degree in 1986 and a Ph.D. in the year 1989. Before joining IIT Madras in 2000, he was employed at Mississippi State University. He has over 400 technical publications (including 200 refereed journal papers), 16 patents filings and has directed 22 PHD student dissertations and 46 MS student theses. In recognition for his outstanding contributions to research in the field of Nondestructive Evaluation, he was conferred with the ROY SHARPE PRIZE by the British Institute for NDT for the year 2012. He was also awarded the ISTEM Entrepreneurial Faculty Member Award for his entrepreneurial activities by Auburn University, USA in 2011 and the NATIONAL NDT AWARD 2010 by the Indian Society for NDT. He also was conferred the DRDO Academy Excellence Award for 2015. He has also been bestowed with the prestigious ABDUL KALAM National Technology Innovation Fellowship in 2018. He has been instrumental in the incubation of several startups including Dhvani Research, Playns Technologies, Detect Technologies, Maximl Labs, Trotix Robotics, HyperVerge, and OP Tech and has jointly developed several new products through these companies. He currently serves as the Editor-in-Chief of the Journal for Nondestructive Evaluation (ISNT) and as the South-east Asia Editor for the Journal of Nondestructive Testing and Evaluation (Taylor and Francis). He also serves as the Associate Editor of Ultrasonics (Elsevier) and serves in the editorial board of the Journal of Structural Longevity (Techscience). He also is a board member of the World Federation of NDE Centers and the QNDE Scientific Advisor Committee. He is a Life Fellow of the Academia NDT International, Life Fellow of the Indian Society of Nondestructive Testing (ISNT) and a Fellow of the Indian National Academy of Engineers."
  },
  {
    id: 8,
    img: img4,
    title: "dr. jayaprakash sai",
    designation: "Organising Secretary",
    institute: "AIIMS, Apollo, Osmania Medical Collage",
    details: "Prof. Krishnan Balasubramaniam has been involved in the field of Non-destructive evaluation for more than Thirty years with applications in the fields of maintenance, quality assurance, manufacturing and design. His areas of research interests include Nondestructive evaluation, in-process monitoring, structural health monitoring, and applied data analysis. He is currently a Chair Professor in the Department of Mechanical Engineering and the Dean for Industrial Consultancy and Sponsored Research at the Indian Institute of Technology Madras, and also serves as the Head of the Centre for Nondestructive Evaluation which he founded in 2001. He received his undergraduate degree in Mechanical Engineering from the University of Madras (Regional Engineering College, Tiruchirapalli, India) in 1984. He then graduated from Drexel University with a M.S. degree in 1986 and a Ph.D. in the year 1989. Before joining IIT Madras in 2000, he was employed at Mississippi State University. He has over 400 technical publications (including 200 refereed journal papers), 16 patents filings and has directed 22 PHD student dissertations and 46 MS student theses. In recognition for his outstanding contributions to research in the field of Nondestructive Evaluation, he was conferred with the ROY SHARPE PRIZE by the British Institute for NDT for the year 2012. He was also awarded the ISTEM Entrepreneurial Faculty Member Award for his entrepreneurial activities by Auburn University, USA in 2011 and the NATIONAL NDT AWARD 2010 by the Indian Society for NDT. He also was conferred the DRDO Academy Excellence Award for 2015. He has also been bestowed with the prestigious ABDUL KALAM National Technology Innovation Fellowship in 2018. He has been instrumental in the incubation of several startups including Dhvani Research, Playns Technologies, Detect Technologies, Maximl Labs, Trotix Robotics, HyperVerge, and OP Tech and has jointly developed several new products through these companies. He currently serves as the Editor-in-Chief of the Journal for Nondestructive Evaluation (ISNT) and as the South-east Asia Editor for the Journal of Nondestructive Testing and Evaluation (Taylor and Francis). He also serves as the Associate Editor of Ultrasonics (Elsevier) and serves in the editorial board of the Journal of Structural Longevity (Techscience). He also is a board member of the World Federation of NDE Centers and the QNDE Scientific Advisor Committee. He is a Life Fellow of the Academia NDT International, Life Fellow of the Indian Society of Nondestructive Testing (ISNT) and a Fellow of the Indian National Academy of Engineers."
  }
]
